# Generated by Django 4.2.17 on 2024-12-08 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_personal_client_phone_delete_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
