# Generated by Django 4.2.17 on 2024-12-09 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_personal_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField(verbose_name='Дата записи')),
                ('appointment_time', models.TimeField(verbose_name='Время записи')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.client', verbose_name='Клиент')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.personal', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'unique_together': {('personal', 'appointment_date', 'appointment_time')},
            },
        ),
    ]
