# Generated by Django 4.0 on 2024-12-10 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_service_delete_communication'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиента', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='personal',
            options={'verbose_name': 'сотрудника', 'verbose_name_plural': 'Сотрудники'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'услугу', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
        migrations.AlterField(
            model_name='service',
            name='duration',
            field=models.DurationField(verbose_name='Продолжительность'),
        ),
        migrations.AlterField(
            model_name='service',
            name='personal',
            field=models.ManyToManyField(to='crm.Personal', verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
