# Generated by Django 4.0 on 2024-12-10 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_alter_appointment_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.service', verbose_name='Услуга'),
        ),
    ]
