# Generated by Django 4.0 on 2024-12-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_appointment_service'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('personal', 'appointment_date', 'appointment_time'), name='unique_appointment'),
        ),
    ]
