# Generated by Django 4.0 on 2024-12-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_appointment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Выполнена'), ('rejected', 'Отклонена')], default='pending', max_length=20, verbose_name='Статус записи'),
        ),
    ]
