# Generated by Django 4.0 on 2024-12-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'В ожидании'), ('completed', 'Выполнено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус записи'),
        ),
    ]
