# Generated by Django 4.0 on 2024-12-12 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Appointments'},
        ),
    ]
