# Generated by Django 4.0 on 2024-12-12 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_appointment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
