# Generated by Django 4.0 on 2024-12-13 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0018_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('выполнено', 'Выполнено'), ('отклонено', 'Отклонено')], default='в ожидании', max_length=20, verbose_name='Статус записи'),
        ),
    ]
