# Generated by Django 4.0 on 2024-12-13 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crm.personal', verbose_name='Сотрудник'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.service', verbose_name='Услуга'),
        ),
    ]
