# Generated by Django 5.1.4 on 2024-12-17 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_alter_service_duration_alter_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='personal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='crm.personal', verbose_name='Сотрудник'),
        ),
    ]
