# Generated by Django 5.1.4 on 2024-12-19 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_alter_appointment_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='personal',
            name='status',
            field=models.CharField(choices=[('работает', 'Работает'), ('уволен', 'Уволен')], default='работает', max_length=20, verbose_name='Статус'),
        ),
    ]
