# Generated by Django 5.1.4 on 2024-12-23 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_servicereport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicereport',
            options={'verbose_name': 'Отчет по услугам', 'verbose_name_plural': 'Отчеты по услугам'},
        ),
    ]
