# Generated by Django 5.1.4 on 2024-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0026_workschedule'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='workschedule',
            name='unique_work_schedule',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='work_date',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='day_of_week',
            field=models.CharField(choices=[('Понедельник', 'Понедельник'), ('Вторник', 'Вторник'), ('Среда', 'Среда'), ('Четверг', 'Четверг'), ('Пятница', 'Пятница'), ('Суббота', 'Суббота'), ('Воскресенье', 'Воскресенье')], default='Понедельник', max_length=15, verbose_name='День недели'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='workschedule',
            constraint=models.UniqueConstraint(fields=('personal', 'day_of_week'), name='unique_work_schedule'),
        ),
    ]
