# Generated by Django 5.1.4 on 2024-12-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_remove_workschedule_unique_work_schedule_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkSchedule',
        ),
    ]
