# Generated by Django 5.1.4 on 2024-12-27 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0028_delete_workschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_date', models.DateField(verbose_name='Дата')),
                ('start_time', models.TimeField(verbose_name='Начало рабочего дня')),
                ('end_time', models.TimeField(verbose_name='Конец рабочего дня')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.personal', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'График работы',
                'verbose_name_plural': 'Графики работы',
                'constraints': [models.UniqueConstraint(fields=('personal', 'work_date'), name='unique_work_schedule')],
            },
        ),
    ]
