# Generated by Django 5.1.4 on 2024-12-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0029_workschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'график работы', 'verbose_name_plural': 'Графики работы'},
        ),
        migrations.RemoveConstraint(
            model_name='workschedule',
            name='unique_work_schedule',
        ),
        migrations.RenameField(
            model_name='workschedule',
            old_name='work_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='workschedule',
            name='is_day_off',
            field=models.BooleanField(default=False, verbose_name='Выходной'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время окончания работы'),
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время начала работы'),
        ),
        migrations.AlterUniqueTogether(
            name='workschedule',
            unique_together={('personal', 'date')},
        ),
    ]
