# Generated by Django 5.1.4 on 2024-12-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата'),
        ),
    ]
