# Generated by Django 5.1.5 on 2025-05-06 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_alter_workschedule_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть формата +375XXXXXXXXX', regex='^\\+?375\\d{9}$')], verbose_name='Телефон'),
        ),
    ]
