# Generated by Django 5.1.5 on 2025-07-17 19:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_alter_client_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('в ожидании', 'В ожидании'), ('выполнено', 'Выполнено')], default='в ожидании', max_length=20, verbose_name='Статус записи'),
        ),
        migrations.AlterField(
            model_name='client',
            name='birth_date',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Телефон должен быть формата +375(29|33|44|25)XXXXXXX', regex='^\\+375(29|33|44|25)\\d{7}$')]),
        ),
    ]
